import { IData } from "./interface";

export const campaignData: IData[] = [
  {
    userID: "u-1",
    displayName: "Jone",
    picture: "",
    score: 157000,
    originalIndex: 0,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-2",
    displayName: "Victoria",
    picture: "",
    score: 46200,
    originalIndex: 1,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-3",
    displayName: "Joy",
    picture: "",
    score: 38800,
    originalIndex: 2,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-4",
    displayName: "Quinn",
    picture: "",
    score: 33400,
    originalIndex: 3,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-5",
    displayName: "Sheenalo",
    picture: "",
    score: 31600,
    originalIndex: 4,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-6",
    displayName: "Charlene",
    picture: "",
    score: 30800,
    originalIndex: 5,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-7",
    displayName: "LeonaBaby",
    picture: "",
    score: 22300,
    originalIndex: 6,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-8",
    displayName: "Sunny",
    picture: "",
    score: 17800,
    originalIndex: 7,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-9",
    displayName: "ImWord",
    picture: "",
    score: 17300,
    originalIndex: 8,
    translateY: 0,
    additionalIndex: 0,
  },
  {
    userID: "u-10",
    displayName: "Dophine",
    picture: "",
    score: 15400,
    originalIndex: 9,
    translateY: 0,
    additionalIndex: 0,
  },
];
